# Generated by Django 2.2.13 on 2023-01-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230125_0122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfessionImage',
        ),
        migrations.AddField(
            model_name='profession',
            name='image',
            field=models.ImageField(default=123, upload_to='img'),
            preserve_default=False,
        ),
    ]
