# Generated by Django 2.2.13 on 2023-01-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
    ]
